"""Static LeetCode slug -> difficulty ('E'/'M'/'H') lookup, used by build_data.py
to color a solved item's row by difficulty. Compiled from known problem
difficulty at time of writing; extend as new LeetCode URLs are added to any
sheet. Unlisted slugs (and all non-LeetCode URLs) simply get no difficulty
color -- this is intentionally a best-effort lookup, not a hard dependency.
"""

LC_DIFFICULTY = {
    "01-matrix": "M", "132-pattern": "M", "24-game": "H", "3sum": "M",
    "3sum-closest": "M", "4sum": "M", "4sum-ii": "M", "accounts-merge": "M",
    "add-one-row-to-tree": "M", "add-two-numbers": "M", "add-two-numbers-ii": "M",
    "additive-number": "M", "advantage-shuffle": "M", "alien-dictionary": "H",
    "all-ancestors-of-a-node-in-a-directed-acyclic-graph": "M",
    "all-nodes-distance-k-in-binary-tree": "M", "all-oone-data-structure": "H",
    "all-paths-from-source-to-target": "M", "all-possible-full-binary-trees": "M",
    "amount-of-time-for-binary-tree-to-be-infected": "M", "arithmetic-slices": "M",
    "arithmetic-slices-ii-subsequence": "H", "array-of-doubled-pairs": "M",
    "as-far-from-land-as-possible": "M", "asteroid-collision": "M",
    "average-of-levels-in-binary-tree": "E", "backspace-string-compare": "E",
    "bag-of-tokens": "M", "balance-a-binary-search-tree": "M",
    "balanced-binary-tree": "E", "baseball-game": "E", "basic-calculator": "H",
    "basic-calculator-ii": "M", "basic-calculator-iii": "H", "basic-calculator-iv": "H",
    "best-sightseeing-pair": "M", "best-time-to-buy-and-sell-stock": "E",
    "best-time-to-buy-and-sell-stock-ii": "M", "best-time-to-buy-and-sell-stock-iii": "H",
    "best-time-to-buy-and-sell-stock-iv": "H",
    "best-time-to-buy-and-sell-stock-with-cooldown": "M",
    "best-time-to-buy-and-sell-stock-with-transaction-fee": "M",
    "binary-search": "E", "binary-search-tree-iterator": "M",
    "binary-subarrays-with-sum": "M", "binary-tree-cameras": "H",
    "binary-tree-level-order-traversal": "M", "binary-tree-maximum-path-sum": "H",
    "binary-tree-pruning": "M", "binary-tree-right-side-view": "M",
    "binary-tree-zigzag-level-order-traversal": "M",
    "bitwise-and-of-numbers-range": "M", "boats-to-save-people": "M",
    "booking-concert-tickets-in-groups": "H", "break-a-palindrome": "M",
    "brick-wall": "M", "bricks-falling-when-hit": "H", "broken-calculator": "M",
    "build-an-array-with-stack-operations": "M", "bulb-switcher": "M",
    "burst-balloons": "H", "bus-routes": "H", "camelcase-matching": "M",
    "can-i-win": "M", "candy": "H", "capacity-to-ship-packages-within-d-days": "M",
    "car-fleet": "M", "car-fleet-ii": "H", "car-pooling": "M",
    "cat-and-mouse-ii": "H", "cheapest-flights-within-k-stops": "M",
    "check-completeness-of-a-binary-tree": "M",
    "check-if-a-string-contains-all-binary-codes-of-size-k": "M",
    "check-if-array-pairs-are-divisible-by-k": "M",
    "check-if-there-is-a-valid-partition-for-the-array": "M",
    "check-if-there-is-a-valid-path-in-a-grid": "M",
    "check-if-word-is-valid-after-substitutions": "M",
    "checking-existence-of-edge-length-limited-paths": "H", "cherry-pickup": "H",
    "cherry-pickup-ii": "H", "climbing-stairs": "E", "clone-graph": "M",
    "coin-change": "M", "coin-change-ii": "M", "coloring-a-border": "M",
    "combination-sum": "M", "combination-sum-ii": "M", "combination-sum-iii": "M",
    "combination-sum-iv": "M", "combinations": "M", "compare-version-numbers": "M",
    "complete-binary-tree-inserter": "M", "concatenated-words": "H",
    "concatenation-of-consecutive-binary-numbers": "M", "confusing-number-ii": "H",
    "connecting-cities-with-minimum-cost": "M", "constrained-subsequence-sum": "H",
    "construct-binary-tree-from-inorder-and-postorder-traversal": "M",
    "construct-binary-tree-from-preorder-and-inorder-traversal": "M",
    "construct-binary-tree-from-preorder-and-postorder-traversal": "M",
    "construct-string-from-binary-tree": "E", "container-with-most-water": "M",
    "contains-duplicate": "E", "contiguous-array": "M", "continuous-subarray-sum": "M",
    "continuous-subarrays": "M",
    "convert-binary-number-in-a-linked-list-to-integer": "E",
    "convert-bst-to-greater-tree": "M", "copy-list-with-random-pointer": "M",
    "corporate-flight-bookings": "M", "count-complete-subarrays-in-an-array": "M",
    "count-complete-tree-nodes": "M", "count-days-without-meetings": "M",
    "count-good-triplets-in-an-array": "H", "count-integers-in-intervals": "H",
    "count-integers-with-even-digit-sum": "E",
    "count-negative-numbers-in-a-sorted-matrix": "E",
    "count-number-of-nice-subarrays": "M", "count-number-of-texts": "M",
    "count-number-of-ways-to-place-houses": "M", "count-of-integers": "H",
    "count-of-range-sum": "H", "count-of-smaller-numbers-after-self": "H",
    "count-pairs-with-xor-in-a-range": "H", "count-sorted-vowel-strings": "M",
    "count-square-submatrices-with-all-ones": "M", "count-sub-islands": "M",
    "count-subarrays-where-max-element-appears-at-least-k-times": "M",
    "count-submatrices-with-all-ones": "M",
    "count-substrings-that-differ-by-one-character": "M",
    "count-subtrees-with-max-distance-between-cities": "H",
    "count-the-number-of-complete-components": "M",
    "count-triplets-that-can-form-two-arrays-of-equal-xor": "M",
    "count-unique-characters-of-all-substrings-of-a-given-string": "H",
    "count-ways-to-build-good-strings": "M", "counting-bits": "E",
    "couples-holding-hands": "H", "course-schedule": "M", "course-schedule-ii": "M",
    "course-schedule-iii": "H", "course-schedule-iv": "M",
    "cousins-in-binary-tree": "E", "crawler-log-folder": "E",
    "create-maximum-number": "H", "create-sorted-array-through-instructions": "H",
    "critical-connections-in-a-network": "H", "custom-sort-string": "M",
    "cut-off-trees-for-golf-event": "H", "daily-temperatures": "M",
    "data-stream-as-disjoint-intervals": "H", "decode-string": "M",
    "decode-ways": "M", "decode-ways-ii": "H", "deepest-leaves-sum": "M",
    "delete-and-earn": "M", "delete-columns-to-make-sorted-iii": "H",
    "delete-duplicate-folders-in-system": "H", "delete-node-in-a-bst": "M",
    "delete-node-in-a-linked-list": "E", "delete-operation-for-two-strings": "M",
    "describe-the-painting": "M", "design-a-food-rating-system": "M",
    "design-a-leaderboard": "M", "design-a-number-container-system": "M",
    "design-a-stack-with-increment-operation": "M",
    "design-add-and-search-words-data-structure": "M",
    "design-authentication-manager": "M", "design-browser-history": "M",
    "design-circular-deque": "M", "design-circular-queue": "M",
    "design-file-system": "M", "design-front-middle-back-queue": "M",
    "design-hashmap": "E", "design-hit-counter": "M",
    "design-in-memory-file-system": "H", "design-linked-list": "M",
    "design-log-storage-system": "M", "design-search-autocomplete-system": "H",
    "design-skiplist": "H", "design-twitter": "M", "design-underground-system": "M",
    "determine-if-two-strings-are-close": "M",
    "detonate-the-maximum-bombs": "H", "diameter-of-binary-tree": "E",
    "diameter-of-n-ary-tree": "M", "different-ways-to-add-parentheses": "M",
    "dinner-plate-stacks": "H", "distant-barcodes": "M",
    "distinct-echo-substrings": "H", "distinct-subsequences": "H",
    "distribute-coins-in-binary-tree": "M",
    "divide-array-in-sets-of-k-consecutive-numbers": "M",
    "divide-intervals-into-minimum-number-of-groups": "M",
    "divide-nodes-into-the-maximum-number-of-groups": "H",
    "divide-two-integers": "M", "divisor-game": "E", "dungeon-game": "H",
    "edit-distance": "M", "employee-free-time": "H", "employee-importance": "M",
    "encode-and-decode-tinyurl": "M", "encrypt-and-decrypt-strings": "H",
    "erect-the-fence": "M", "escape-a-large-maze": "H", "evaluate-division": "M",
    "evaluate-reverse-polish-notation": "M", "even-odd-tree": "M",
    "exam-room": "M", "exclusive-time-of-functions": "M",
    "expression-add-operators": "H", "fair-distribution-of-cookies": "M",
    "falling-squares": "H", "fibonacci-number": "E",
    "filling-bookcase-shelves": "M",
    "final-prices-with-a-special-discount-in-a-shop": "E",
    "find-a-peak-element-ii": "M", "find-all-anagrams-in-a-string": "M",
    "find-all-duplicates-in-an-array": "M",
    "find-all-numbers-disappeared-in-an-array": "E",
    "find-all-people-with-secret": "H",
    "find-all-possible-recipes-from-given-supplies": "M",
    "find-champion-ii": "E",
    "find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree": "H",
    "find-duplicate-subtrees": "M", "find-eventual-safe-states": "M",
    "find-first-and-last-position-of-element-in-sorted-array": "M",
    "find-if-path-exists-in-graph": "E", "find-k-closest-elements": "M",
    "find-k-pairs-with-smallest-sums": "M", "find-k-th-smallest-pair-distance": "H",
    "find-largest-value-in-each-tree-row": "M", "find-median-from-data-stream": "H",
    "find-minimum-in-rotated-sorted-array": "M",
    "find-minimum-in-rotated-sorted-array-ii": "H", "find-peak-element": "M",
    "find-players-with-zero-or-one-losses": "M", "find-right-interval": "M",
    "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance": "M",
    "find-the-duplicate-number": "M",
    "find-the-index-of-the-first-occurrence-in-a-string": "E",
    "find-the-safest-path-in-a-grid": "M", "find-the-shortest-superstring": "H",
    "find-the-smallest-divisor-given-a-threshold": "M",
    "find-two-non-overlapping-sub-arrays-each-with-target-sum": "M",
    "find-xor-sum-of-all-pairs-bitwise-and": "H", "first-missing-positive": "H",
    "flatten-a-multilevel-doubly-linked-list": "M",
    "flatten-binary-tree-to-linked-list": "M", "flatten-nested-list-iterator": "M",
    "flip-equivalent-binary-trees": "M", "flood-fill": "E",
    "fraction-to-recurring-decimal": "M", "frequency-of-the-most-frequent-element": "M",
    "frog-jump": "H", "fruit-into-baskets": "M", "furthest-building-you-can-reach": "M",
    "game-of-life": "M", "gas-station": "M", "gcd-sort-of-an-array": "H",
    "generate-parentheses": "M", "get-the-maximum-score": "H",
    "graph-connectivity-with-threshold": "H", "gray-code": "M",
    "grid-illumination": "H", "group-anagrams": "M",
    "group-the-people-given-the-group-size-they-belong-to": "M",
    "grumpy-bookstore-owner": "M", "h-index": "M", "h-index-ii": "M",
    "hand-of-straights": "M", "handling-sum-queries-after-update": "H",
    "happy-number": "E", "house-robber": "M", "house-robber-ii": "M",
    "house-robber-iii": "M", "implement-magic-dictionary": "M",
    "implement-rand10-using-rand7": "M", "implement-trie-prefix-tree": "M",
    "increasing-order-search-tree": "E", "index-pairs-of-a-string": "E",
    "insert-delete-getrandom-o1": "M",
    "insert-delete-getrandom-o1-duplicates-allowed": "H", "insert-interval": "M",
    "insert-into-a-binary-search-tree": "M", "insertion-sort-list": "M",
    "integer-break": "M", "integer-replacement": "M",
    "integer-to-english-words": "H", "interleaving-string": "M",
    "intersection-of-two-arrays": "E", "intersection-of-two-linked-lists": "E",
    "interval-list-intersections": "M", "invert-binary-tree": "E", "ipo": "H",
    "is-graph-bipartite": "M", "is-subsequence": "E", "island-perimeter": "E",
    "isomorphic-strings": "E", "iterator-for-combination": "M", "jump-game": "M",
    "jump-game-ii": "M", "jump-game-iii": "M", "jump-game-iv": "H",
    "jump-game-vi": "M", "k-concatenation-maximum-sum": "M",
    "k-diff-pairs-in-an-array": "M", "k-radius-subarray-averages": "M",
    "k-th-smallest-prime-fraction": "H", "keys-and-rooms": "M",
    "koko-eating-bananas": "M", "kth-ancestor-of-a-tree-node": "H",
    "kth-largest-element-in-a-stream": "E", "kth-largest-element-in-an-array": "M",
    "kth-missing-positive-number": "E", "kth-smallest-element-in-a-bst": "M",
    "kth-smallest-element-in-a-sorted-matrix": "M",
    "largest-color-value-in-a-directed-graph": "H",
    "largest-component-size-by-common-factor": "H", "largest-divisible-subset": "M",
    "largest-number": "M", "largest-rectangle-in-histogram": "H",
    "last-day-where-you-can-still-cross": "H", "last-stone-weight": "E",
    "last-stone-weight-ii": "M", "leaf-similar-trees": "E",
    "length-of-longest-subarray-with-at-most-k-frequency": "M",
    "letter-combinations-of-a-phone-number": "M",
    "lexicographically-smallest-equivalent-string": "M", "lfu-cache": "H",
    "linked-list-cycle": "E", "linked-list-cycle-ii": "M",
    "linked-list-in-binary-tree": "M", "linked-list-random-node": "M",
    "longest-arithmetic-subsequence": "M",
    "longest-chunked-palindrome-decomposition": "H",
    "longest-common-subsequence": "M", "longest-consecutive-sequence": "M",
    "longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit": "M",
    "longest-duplicate-substring": "H", "longest-happy-prefix": "H",
    "longest-happy-string": "M", "longest-harmonious-subsequence": "E",
    "longest-increasing-path-in-a-matrix": "H", "longest-increasing-subsequence": "M",
    "longest-increasing-subsequence-ii": "H", "longest-nice-subarray": "M",
    "longest-palindromic-subsequence": "M", "longest-palindromic-substring": "M",
    "longest-path-with-different-adjacent-characters": "H",
    "longest-repeating-character-replacement": "M", "longest-string-chain": "M",
    "longest-subarray-of-1s-after-deleting-one-element": "M",
    "longest-substring-of-one-repeating-character": "H",
    "longest-substring-without-repeating-characters": "M",
    "longest-univalue-path": "M", "longest-valid-parentheses": "H",
    "longest-well-performing-interval": "M", "longest-word-in-dictionary": "E",
    "longest-zigzag-path-in-a-binary-tree": "M", "loud-and-rich": "M",
    "lowest-common-ancestor-of-a-binary-search-tree": "M",
    "lowest-common-ancestor-of-a-binary-tree": "M", "lru-cache": "M",
    "magnetic-force-between-two-balls": "M", "majority-element": "E",
    "majority-element-ii": "M", "make-array-strictly-increasing": "H",
    "making-a-large-island": "H", "map-of-highest-peak": "M",
    "map-sum-pairs": "M", "matchsticks-to-square": "M", "matrix-block-sum": "M",
    "max-area-of-island": "M", "max-consecutive-ones-iii": "M",
    "max-number-of-k-sum-pairs": "M", "max-points-on-a-line": "H",
    "maximal-rectangle": "H", "maximal-square": "M",
    "maximize-sum-of-array-after-k-negations": "E",
    "maximum-alternating-subsequence-sum": "M", "maximum-average-pass-ratio": "M",
    "maximum-depth-of-binary-tree": "E",
    "maximum-difference-between-node-and-ancestor": "M",
    "maximum-erasure-value": "M", "maximum-frequency-stack": "H",
    "maximum-gap": "M", "maximum-genetic-difference-query": "H",
    "maximum-height-by-stacking-cuboids": "H",
    "maximum-length-of-a-concatenated-string-with-unique-characters": "M",
    "maximum-length-of-pair-chain": "M", "maximum-length-of-repeated-subarray": "M",
    "maximum-non-negative-product-in-a-matrix": "M",
    "maximum-number-of-achievable-transfer-requests": "H",
    "maximum-number-of-eaten-apples": "M",
    "maximum-number-of-events-that-can-be-attended": "M",
    "maximum-number-of-events-that-can-be-attended-ii": "H",
    "maximum-number-of-non-overlapping-substrings": "H",
    "maximum-number-of-removable-characters": "M",
    "maximum-number-of-robots-within-budget": "H",
    "maximum-number-of-vowels-in-a-substring-of-given-length": "M",
    "maximum-performance-of-a-team": "H",
    "maximum-points-you-can-obtain-from-cards": "M", "maximum-population-year": "E",
    "maximum-product-of-the-length-of-two-palindromic-subsequences": "M",
    "maximum-product-of-word-lengths": "M", "maximum-product-subarray": "M",
    "maximum-profit-in-job-scheduling": "H", "maximum-rows-covered-by-columns": "M",
    "maximum-score-words-formed-by-letters": "H",
    "maximum-segment-sum-after-removals": "H",
    "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold": "M",
    "maximum-size-subarray-sum-equals-k": "M", "maximum-students-taking-exam": "H",
    "maximum-subarray": "M", "maximum-subarray-min-product": "M",
    "maximum-subsequence-score": "M", "maximum-sum-bst-in-binary-tree": "H",
    "maximum-sum-circular-subarray": "M",
    "maximum-sum-of-two-non-overlapping-subarrays": "M",
    "maximum-sum-queries": "H", "maximum-swap": "M",
    "maximum-value-of-k-coins-from-piles": "H", "maximum-width-of-binary-tree": "M",
    "maximum-width-ramp": "M", "maximum-xor-of-two-numbers-in-an-array": "M",
    "maximum-xor-with-an-element-from-array": "H",
    "median-of-two-sorted-arrays": "H", "meeting-rooms": "E",
    "meeting-rooms-ii": "M", "meeting-scheduler": "M",
    "merge-in-between-linked-lists": "M", "merge-intervals": "M",
    "merge-k-sorted-lists": "H", "merge-similar-items": "E",
    "merge-sorted-array": "E", "merge-triplets-to-form-target-triplet": "M",
    "merge-two-binary-trees": "E", "merge-two-sorted-lists": "E",
    "middle-of-the-linked-list": "E", "min-cost-climbing-stairs": "E",
    "min-cost-to-connect-all-points": "M", "min-stack": "M",
    "minimize-malware-spread-ii": "H", "minimize-maximum-of-array": "M",
    "minimize-maximum-pair-sum-in-array": "M",
    "minimized-maximum-of-products-distributed-to-any-store": "M",
    "minimum-add-to-make-parentheses-valid": "M",
    "minimum-area-rectangle-ii": "M",
    "minimum-ascii-delete-sum-for-two-strings": "M",
    "minimum-consecutive-cards-to-pick-up": "M", "minimum-cost-for-tickets": "M",
    "minimum-cost-to-connect-two-groups-of-points": "H",
    "minimum-cost-to-cut-a-stick": "H", "minimum-cost-to-hire-k-workers": "H",
    "minimum-cost-to-make-at-least-one-valid-path-in-a-grid": "H",
    "minimum-cost-tree-from-leaf-values": "M",
    "minimum-deletion-cost-to-avoid-repeating-letters": "M",
    "minimum-deletions-to-make-character-frequencies-unique": "M",
    "minimum-depth-of-binary-tree": "E", "minimum-deviation-in-array": "H",
    "minimum-difficulty-of-a-job-schedule": "H",
    "minimum-distance-between-bst-nodes": "E", "minimum-falling-path-sum": "M",
    "minimum-flips-to-make-a-or-b-equal-to-c": "M", "minimum-genetic-mutation": "M",
    "minimum-height-trees": "M", "minimum-incompatibility": "H",
    "minimum-increment-to-make-array-unique": "M",
    "minimum-insertion-steps-to-make-a-string-palindrome": "H",
    "minimum-limit-of-balls-in-a-bag": "M",
    "minimum-moves-to-make-array-complementary": "M",
    "minimum-number-of-arrows-to-burst-balloons": "M",
    "minimum-number-of-days-to-make-m-bouquets": "M",
    "minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix": "H",
    "minimum-number-of-k-consecutive-bit-flips": "H",
    "minimum-number-of-moves-to-make-palindrome": "H",
    "minimum-number-of-operations-to-make-array-xor-equal-to-k": "M",
    "minimum-number-of-operations-to-make-string-sorted": "H",
    "minimum-number-of-refueling-stops": "H",
    "minimum-number-of-removals-to-make-mountain-array": "H",
    "minimum-number-of-swaps-to-make-the-string-balanced": "M",
    "minimum-number-of-taps-to-open-to-water-a-garden": "H",
    "minimum-number-of-visited-cells-in-a-grid": "H",
    "minimum-obstacle-removal-to-reach-corner": "H",
    "minimum-operations-to-make-the-array-k-increasing": "H",
    "minimum-operations-to-reduce-x-to-zero": "M", "minimum-path-cost-in-a-grid": "M",
    "minimum-path-sum": "M", "minimum-remove-to-make-valid-parentheses": "M",
    "minimum-score-of-a-path-between-two-cities": "M",
    "minimum-score-triangulation-of-polygon": "M", "minimum-sideway-jumps": "M",
    "minimum-size-subarray-sum": "M", "minimum-speed-to-arrive-on-time": "M",
    "minimum-swaps-to-group-all-1s-together": "M",
    "minimum-swaps-to-group-all-1s-together-ii": "M",
    "minimum-swaps-to-make-sequences-increasing": "M",
    "minimum-time-difference": "M", "minimum-time-to-complete-trips": "M",
    "minimum-time-to-visit-a-cell-in-a-grid": "H",
    "minimum-window-subsequence": "H", "minimum-window-substring": "H",
    "missing-number": "E", "modify-graph-edge-weights": "H",
    "most-stones-removed-with-same-row-or-column": "M", "move-zeroes": "E",
    "moving-average-from-data-stream": "E", "my-calendar-i": "M",
    "my-calendar-ii": "M", "my-calendar-iii": "H", "n-queens": "H",
    "n-queens-ii": "H", "n-th-tribonacci-number": "E",
    "nearest-exit-from-entrance-in-maze": "M", "network-delay-time": "M",
    "next-greater-element-i": "E", "next-greater-element-ii": "M",
    "next-greater-node-in-linked-list": "M", "nim-game": "E",
    "non-decreasing-subsequences": "M",
    "non-negative-integers-without-consecutive-ones": "H",
    "non-overlapping-intervals": "M", "nth-magical-number": "H",
    "number-of-atoms": "H", "number-of-boomerangs": "M",
    "number-of-closed-islands": "M", "number-of-dice-rolls-with-target-sum": "M",
    "number-of-digit-one": "H", "number-of-distinct-substrings-in-a-string": "H",
    "number-of-enclaves": "M", "number-of-equivalent-domino-pairs": "E",
    "number-of-flowers-in-full-bloom": "H", "number-of-good-paths": "H",
    "number-of-good-ways-to-split-a-string": "M",
    "number-of-increasing-paths-in-a-grid": "H", "number-of-islands": "M",
    "number-of-longest-increasing-subsequence": "M",
    "number-of-matching-subsequences": "M", "number-of-orders-in-the-backlog": "M",
    "number-of-pairs-satisfying-inequality": "H", "number-of-provinces": "M",
    "number-of-restricted-paths-from-first-to-last-node": "M",
    "number-of-sets-of-k-non-overlapping-line-segments": "M",
    "number-of-squareful-arrays": "M", "number-of-sub-arrays-with-odd-sum": "M",
    "number-of-submatrices-that-sum-to-target": "H",
    "number-of-substrings-containing-all-three-characters": "M",
    "number-of-unique-good-subsequences": "H", "number-of-valid-subarrays": "H",
    "number-of-ways-to-arrive-at-destination": "M",
    "number-of-ways-to-reach-a-position-after-exactly-k-steps": "M",
    "number-of-ways-to-wear-different-hats-to-each-other": "H",
    "numbers-at-most-n-given-digit-set": "H", "numbers-with-repeated-digits": "H",
    "numbers-with-same-consecutive-differences": "M", "odd-even-jump": "H",
    "odd-even-linked-list": "M", "ones-and-zeroes": "M", "online-election": "M",
    "online-majority-element-in-subarray": "H", "online-stock-span": "M",
    "open-the-lock": "M", "pacific-atlantic-water-flow": "M", "paint-house": "M",
    "paint-house-ii": "H", "paint-house-iii": "H", "painting-the-walls": "H",
    "palindrome-linked-list": "E", "palindrome-number": "E", "palindrome-pairs": "H",
    "palindrome-partitioning": "M", "palindrome-partitioning-ii": "H",
    "palindrome-partitioning-iii": "H", "palindrome-partitioning-iv": "H",
    "palindromic-substrings": "M", "pancake-sorting": "M",
    "parallel-courses-ii": "H", "parallel-courses-iii": "H",
    "partition-array-into-two-arrays-to-minimize-sum-difference": "H",
    "partition-equal-subset-sum": "M", "partition-labels": "M",
    "partition-list": "M", "partition-to-k-equal-sum-subsets": "M",
    "patching-array": "H", "path-sum": "E", "path-sum-ii": "M",
    "path-sum-iii": "M", "path-with-maximum-gold": "M",
    "path-with-maximum-probability": "M", "path-with-minimum-effort": "M",
    "peak-index-in-a-mountain-array": "M", "peeking-iterator": "M",
    "perfect-squares": "M", "permutation-in-string": "M",
    "permutation-sequence": "H", "permutations": "M", "permutations-ii": "M",
    "plates-between-candles": "M", "plus-one": "E",
    "points-that-intersect-with-cars": "E",
    "populating-next-right-pointers-in-each-node": "M",
    "populating-next-right-pointers-in-each-node-ii": "M",
    "possible-bipartition": "M", "powx-n": "M", "predict-the-winner": "M",
    "prefix-and-suffix-search": "H", "process-restricted-friend-requests": "H",
    "process-tasks-using-servers": "M", "product-of-array-except-self": "M",
    "product-of-the-last-k-numbers": "M", "profitable-schemes": "H",
    "pseudo-palindromic-paths-in-a-binary-tree": "M",
    "queue-reconstruction-by-height": "M", "race-car": "H",
    "random-pick-index": "M", "random-pick-with-blacklist": "H",
    "random-pick-with-weight": "M", "range-addition": "M",
    "range-frequency-queries": "M", "range-module": "H", "range-sum-of-bst": "E",
    "range-sum-query-2d-mutable": "H", "range-sum-query-immutable": "E",
    "range-sum-query-mutable": "M", "rank-transform-of-an-array": "E",
    "ransom-note": "E", "reachable-nodes-in-subdivided-graph": "H",
    "reconstruct-itinerary": "H", "recover-a-tree-from-preorder-traversal": "M",
    "recover-binary-search-tree": "M", "rectangle-area": "M",
    "rectangle-area-ii": "H", "reduce-array-size-to-the-half": "M",
    "reducing-dishes": "H", "reduction-operations-to-make-the-array-elements-equal": "M",
    "redundant-connection": "M", "redundant-connection-ii": "H",
    "regions-cut-by-slashes": "M", "regular-expression-matching": "H",
    "relative-sort-array": "E", "remove-all-adjacent-duplicates-in-string": "E",
    "remove-all-adjacent-duplicates-in-string-ii": "M", "remove-boxes": "H",
    "remove-covered-intervals": "M", "remove-duplicate-letters": "M",
    "remove-duplicates-from-sorted-array": "E",
    "remove-duplicates-from-sorted-array-ii": "M",
    "remove-duplicates-from-sorted-list-ii": "M", "remove-invalid-parentheses": "H",
    "remove-k-digits": "M",
    "remove-max-number-of-edges-to-keep-graph-fully-traversable": "H",
    "remove-nth-node-from-end-of-list": "M", "remove-outermost-parentheses": "E",
    "remove-zero-sum-consecutive-nodes-from-linked-list": "M", "reorder-list": "M",
    "reorganize-string": "M", "repeated-string-match": "M",
    "repeated-substring-pattern": "E", "replace-words": "M",
    "restore-ip-addresses": "M", "restore-the-array": "H", "reverse-bits": "E",
    "reverse-integer": "M", "reverse-linked-list": "E", "reverse-linked-list-ii": "M",
    "reverse-nodes-in-even-length-groups": "M", "reverse-nodes-in-k-group": "H",
    "reverse-pairs": "H", "reverse-vowels-of-a-string": "E",
    "reverse-words-in-a-string": "M", "rotate-array": "M", "rotate-image": "M",
    "rotate-list": "M", "rotate-string": "E", "rotated-digits": "E",
    "rotting-oranges": "M", "russian-doll-envelopes": "H", "same-tree": "E",
    "satisfiability-of-equality-equations": "M", "score-after-flipping-matrix": "M",
    "score-of-parentheses": "M", "scramble-string": "H", "search-a-2d-matrix": "M",
    "search-a-2d-matrix-ii": "M", "search-in-rotated-sorted-array": "M",
    "search-in-rotated-sorted-array-ii": "M", "search-insert-position": "E",
    "search-suggestions-system": "M", "seat-reservation-manager": "M",
    "second-minimum-node-in-a-binary-tree": "E",
    "second-minimum-time-to-reach-destination": "H",
    "sell-diminishing-valued-colored-balls": "M", "sequence-reconstruction": "M",
    "serialize-and-deserialize-binary-tree": "H",
    "serialize-and-deserialize-bst": "M",
    "set-intersection-size-at-least-two": "H", "set-matrix-zeroes": "M",
    "set-mismatch": "E", "shifting-letters-ii": "M", "shopping-offers": "M",
    "short-encoding-of-words": "M", "shortest-bridge": "M",
    "shortest-common-supersequence": "H",
    "shortest-distance-after-road-addition-queries-i": "H",
    "shortest-distance-after-road-addition-queries-ii": "H",
    "shortest-palindrome": "H",
    "shortest-path-in-a-grid-with-obstacles-elimination": "H",
    "shortest-path-in-binary-matrix": "M", "shortest-path-to-get-all-keys": "H",
    "shortest-path-visiting-all-nodes": "H",
    "shortest-path-with-alternating-colors": "M",
    "shortest-subarray-with-sum-at-least-k": "H", "similar-string-groups": "H",
    "simplify-path": "M", "single-element-in-a-sorted-array": "M",
    "single-number": "E", "single-number-ii": "M", "single-number-iii": "M",
    "single-threaded-cpu": "M", "sliding-puzzle": "H", "sliding-window-maximum": "H",
    "sliding-window-median": "H", "smallest-missing-genetic-value-in-each-subtree": "H",
    "smallest-range-covering-elements-from-k-lists": "H",
    "smallest-string-starting-from-leaf": "M", "smallest-string-with-swaps": "M",
    "smallest-sufficient-team": "H", "snakes-and-ladders": "M",
    "snapshot-array": "M", "solving-questions-with-brainpower": "M",
    "sort-array-by-parity": "E", "sort-array-by-parity-ii": "E",
    "sort-characters-by-frequency": "M", "sort-colors": "M",
    "sort-items-by-groups-respecting-dependencies": "H", "sort-list": "M",
    "sort-the-jumbled-numbers": "M",
    "special-array-with-x-elements-greater-than-or-equal-x": "E",
    "spiral-matrix": "M", "spiral-matrix-ii": "M",
    "split-a-string-in-balanced-strings": "E",
    "split-a-string-into-the-max-number-of-unique-substrings": "M",
    "split-array-into-consecutive-subsequences": "M",
    "split-array-into-fibonacci-sequence": "M", "split-array-largest-sum": "H",
    "split-array-with-same-average": "H", "split-linked-list-in-parts": "M",
    "sqrtx": "E", "squares-of-a-sorted-array": "E",
    "step-by-step-directions-from-a-binary-tree-node-to-another": "M",
    "stickers-to-spell-word": "H", "stock-price-fluctuation": "M",
    "stone-game": "M", "stone-game-ii": "M", "stone-game-iii": "H",
    "stone-game-iv": "M", "stone-game-ix": "M", "stone-game-v": "H",
    "stone-game-vi": "M", "stone-game-vii": "M", "stone-game-viii": "H",
    "strange-printer": "H", "stream-of-characters": "H", "string-compression": "M",
    "string-compression-ii": "H", "string-matching-in-an-array": "E",
    "string-to-integer-atoi": "M", "student-attendance-record-ii": "M",
    "subarray-product-less-than-k": "M", "subarray-sum-equals-k": "M",
    "subarray-sums-divisible-by-k": "M", "subarrays-with-k-different-integers": "H",
    "subsets": "M", "subsets-ii": "M", "substring-with-concatenation-of-all-words": "H",
    "subtree-of-another-tree": "E", "sudoku-solver": "H",
    "sum-of-all-odd-length-subarrays": "E", "sum-of-distances-in-tree": "H",
    "sum-of-mutated-array-closest-to-target": "M",
    "sum-of-prefix-scores-of-strings": "H", "sum-of-root-to-leaf-binary-numbers": "E",
    "sum-of-square-numbers": "M", "sum-of-subarray-minimums": "M",
    "sum-of-subarray-ranges": "M", "sum-of-two-integers": "M",
    "sum-root-to-leaf-numbers": "M", "super-egg-drop": "H", "super-ugly-number": "M",
    "surrounded-regions": "M", "swap-nodes-in-pairs": "M",
    "swapping-nodes-in-a-linked-list": "M", "swim-in-rising-water": "H",
    "symmetric-tree": "E", "tallest-billboard": "H", "target-sum": "M",
    "task-scheduler": "M", "teemo-attacking": "E", "text-justification": "H",
    "the-earliest-moment-when-everyone-become-friends": "M",
    "the-number-of-good-subsets": "H", "the-skyline-problem": "H",
    "tiling-a-rectangle-with-the-fewest-squares": "H",
    "time-based-key-value-store": "M", "top-k-frequent-elements": "M",
    "top-k-frequent-words": "M", "total-cost-to-hire-k-workers": "M",
    "total-hamming-distance": "M", "trapping-rain-water": "H", "triangle": "M",
    "trim-a-binary-search-tree": "M", "two-city-scheduling": "M", "two-sum": "E",
    "two-sum-ii-input-array-is-sorted": "M", "two-sum-iv-input-is-a-bst": "E",
    "ugly-number-ii": "M", "uncrossed-lines": "M", "unique-binary-search-trees": "M",
    "unique-binary-search-trees-ii": "M",
    "unique-length-3-palindromic-subsequences": "M", "unique-paths": "M",
    "unique-paths-ii": "M", "unique-paths-iii": "H",
    "unique-substrings-in-wraparound-string": "M", "utf-8-validation": "M",
    "valid-anagram": "E", "valid-number": "H", "valid-palindrome": "E",
    "valid-palindrome-ii": "E", "valid-parentheses": "E",
    "valid-parenthesis-string": "M", "valid-perfect-square": "E",
    "valid-permutations-for-di-sequence": "H", "valid-sudoku": "M",
    "validate-binary-search-tree": "M", "validate-stack-sequences": "M",
    "verbal-arithmetic-puzzle": "H", "vertical-order-traversal-of-a-binary-tree": "H",
    "video-stitching": "M", "walls-and-gates": "M", "where-will-the-ball-fall": "M",
    "wiggle-sort-ii": "M", "wiggle-subsequence": "M", "wildcard-matching": "H",
    "word-break": "M", "word-break-ii": "H", "word-ladder": "H",
    "word-ladder-ii": "H", "word-pattern": "E", "word-search": "M",
    "word-search-ii": "H", "zero-array-transformation-i": "M",
    "zero-array-transformation-ii": "M", "zigzag-conversion": "M",
}
